### ISSUE TITLE
Remove protagonist dependence

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/fury-adapter-apib-parser#6]
I would like to use this adapter with drafter.js, hence removing the hardcoded protagonist dependence. Given that drafter.js is a drop in replacement for protagonist, it shouldn't be that hard. I'm not making a PR as it looks like a breaking change.

**Comment by pksunkara** [comment]
@XVincentX You really don't want to use drafter.js since it is a lot slower than protagonist. Drafter.js is an alternative for people who can't get protagonist to work on their wonky systems. So, we are not going to do this for this package.

But we can add a `try .. catch` to use drafter.js when protagonist fails in this module.

**Comment by XVincentX** [comment]
I disagree. I think there are more interesting use cases for drafter js than a simply replacement for wonky systems.

One of that would be, for example, integrations into common code editor.

[Atom](https://atom.io/) is a totally javascript made editor which is running under nodejs runtime [VSCode](https://code.visualstudio.com) is the same. In order to provide parsing errors, code completion and resource navigation it would be super useful to me to leverage drafter js (and build it into the runtime) and not on CDrafter; I do not really care about speed. Some times eases are far more important than quality/speed.

However, the source code isn't really so big (30 lines), so I guess I will drop it in the extensions themselves and continue from there using drafter; by the way, you might want to make this pluggable.

**Comment by w-vi** [comment]
I agree with @XVincentX here, drafter.js is more then just an alternative for those having issues installing protagonist. @pksunkara currently drafter.js is 3-4 times slower then protagonist so if it takes 50ms on protagonist it takes 150ms using drafter.js unless you are on server or parsing every few milliseconds you don't really notice the difference, especially with tools where you parse once in a while on user request it doesn't matter. I personally think drafter.js should be the default package used and if you install protagonist it will be used like is the case for redis and hiredis.
Speed is important but sometimes it is the computational speed and sometimes installation speed and some times development speed ... 

Oh and I'd like to see how drafter.js/fury works in browser, because you might want to make browser plugins like dredd for example.

**Comment by pksunkara** [comment]
I don't agree with it. Being 75% fast means a lot when people are serving a lot of requests. Imagine how plutonium would be.

As I said before, I am okay with having something like following:

``` js
try {
  parser = require('protagonist');
} catch {
  parser = require('drafter.js');
}
```

When the above solves @XVincentX problem, why do we want to remove protagonist?

**Comment by XVincentX** [comment]
@pksunkara I am totally ok with the solution you proposed, but I am afraid it will not be enough.

If I do not have a C++ compiler or for some reason I'm not able to compile protagonist, the installation will fail. No matter the `try/catch` block.

`fury-adapter-apib-parser` should be just the adapter and kind of decoupled from the parser (drafter.js or CDrafter); given that, what I would suggest is
1. Remove protagonist as dependency, as it will block the installation on some systems

and then
1. `fury-adapter-drafter` should have the parser object injected from outside
2. Use the try/catch solution you proposed, and let the people install a parser in their project itself. You could put a post install echo like `echo "Please install drafter or drafter.js`.

Your call.

**Comment by w-vi** [comment]
@pksunkara How many people need the speed, how many people are running servers with hundreds of requests per minute? Is it most of them? I seriously doubt it most of the users are using tools like dredd and aglio or editors where you hardly need more then 5 requests per minute. Or you have some numbers to back up you argument that speed is the most important thing? Ease of installation is from my point of view more important as that affects the adoption of tools. 
If you are running a server you probably don't mind spending time installing protagonist explicitly. Giving again the example fo redis and hiredis. If you care about speed you explicitly install hiredis to get it and make sure you have the compiler etc ... if you don't you just install the redis package where no compilation takes place and is done straight away like CI where you don't care to save 100ms per request when installing the native addon takes more then 5 minutes.
